### ISSUE TITLE
"Connect Your Wallet" displays Universal Address, not KSM.

### ISSUE THREAD

**Issue by christinammiyar** [rmrk-team/rmrk-kanaria-issues#1]
When connecting your wallet, instead of displaying the address type you have currently selected on the Polkadot Plugin, it displays all addresses as their universal addresses. For some users expecting to see their Kusama address, this could lead to confusion.

![addressIssue](https://user-images.githubusercontent.com/8890067/113047859-d96b0900-916f-11eb-9ab2-09b0c75fde08.jpg)

**Comment by dbpatty** [comment]
me too

**Comment by Yuripetusko** [comment]
This is now fixed. Thanks for reporting. Please if you have time do a quick check and close the ticket if it's fixed

**Comment by christinammiyar** [comment]
Apologies for never seeing this. It is indeed fixed.
