### ISSUE TITLE
Egg Filtering

### ISSUE THREAD

**Issue by J-Cook-jr** [rmrk-team/rmrk-kanaria-issues#6]
When filtering through the LE eggs availability, I noticed the "Claimed" egg Availability filter changes  back to "ALL" when you click the "Next" button. The Next button will take users to the second page of listed eggs, but the filter rules for "Availability" will no longer apply. Also, if the user  tries changing the availability back to "Claimed" while they're still on the second page of listed eggs, the UI will take the user back to the first page. This can cause some frustration to users who are just trying to browse through the claimed list of "Limited Edition" eggs. I haven't checked the other listed eggs pages or filters yet, but I did want to point this out. Hopefully it'll help smoothen the user experience.

**Comment by YuriGii** [comment]
Thanks @J-Cook-jr for reporting, bugfix was just released
